import uuid
from datetime import datetime, timezone
import enum
from typing import Optional
from sqlalchemy import String, DateTime, Boolean, JSON, Text, Enum as SQLEnum
from sqlalchemy.orm import Mapped, mapped_column
from src.db.base import Base


class RuleStatus(str, enum.Enum):
    DRAFT = "DRAFT"          # Generated by LLM / Drafted, awaiting human approval
    APPROVED = "APPROVED"    # Approved by engineer
    REJECTED = "REJECTED"


class RuleSeverity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class Rule(Base):
    __tablename__ = "rules"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4()), index=True
    )
    code: Mapped[str] = mapped_column(String(64), unique=True, index=True, nullable=False)  # e.g. "RULE_AHU_SUPPLY_TEMP_DEV"
    name: Mapped[str] = mapped_column(String(128), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Target Scope: Which equipment or building this rule applies to
    target_scope: Mapped[dict] = mapped_column(JSON, nullable=False)

    # Fault Logic: The conditions, thresholds, duration window (e.g. 15 min)
    fault_logic: Mapped[dict] = mapped_column(JSON, nullable=False)

    severity: Mapped[RuleSeverity] = mapped_column(SQLEnum(RuleSeverity), default=RuleSeverity.MEDIUM)
    is_active: Mapped[bool] = mapped_column(Boolean, default=False)
    status: Mapped[RuleStatus] = mapped_column(SQLEnum(RuleStatus), default=RuleStatus.DRAFT)
    
    created_by: Mapped[str] = mapped_column(String(64), default="system")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )
